### ISSUE TITLE
Duplicate buildbot releases causing hash failures

### ISSUE THREAD

**Issue by magneticflux-** [dolphin-emu/sadm#177]
It seems like Buildbot is building Windows x64 (and possibly more) releases twice and racing to replace the released artifact. If a user or automated system downloads the first build artifact and compares it to a user who downloaded it a few minutes later, the two files differ.

An example of the duplicate builds:
Original: https://dolphin.ci/#/builders/6/builds/2486
Duplicate: https://dolphin.ci/#/builders/6/builds/2488
The only difference I can see between the builds (besides timestamp) is that the second build only marks @delroth as "Responsible", while the first build has 4 users marked.

This causes issues with package managers like Scoop, which download build artifacts and validate their hash. The automated commit https://github.com/Calinou/scoop-games/commit/15cf5b5132f6dc4e13128fa9f368c608bef59d2e claims the artifact from the duplicated build 18271 has SHA256 `e0cc4e6e4da497736b2e0ca6088700ab037848866083d851b984b012151da185`, when the file hosted on the website as "build 18271" has hash `738d372ff81527a7c37a58aa62d9abc2efc68cfb7b8a689e5081829857d08210`.

The Scoop code that computes the hash is located here: https://github.com/ScoopInstaller/Scoop/blob/f93028001fbe5c78cc41f59e3814d2ac8e595724/lib/autoupdate.ps1#L277-L278, and the "Computed hash:" message is printed in this log (use the log search instead of Ctrl+F): https://github.com/Calinou/scoop-games/actions/runs/3954168346/jobs/6771222872

**Comment by magneticflux-** [comment]
This issue seems to have started ~2 weeks ago, and has happened at least 3 times:
https://github.com/Calinou/scoop-games/issues/777
https://github.com/Calinou/scoop-games/issues/785
https://github.com/Calinou/scoop-games/issues/790

**Comment by delroth** [comment]
That will happen whenever we trigger manual rebuilds, which is something we do for a variety of reasons. This has been happening for way more than 2 weeks, in fact it's been happening for years, it's just that we've been doing a ton more active development on our infra recently.

If you want to uphold any property on the artifacts, build them yourselves or at the very least snapshot and mirror them yourselves.

**Comment by delroth** [comment]
(Alternatively: patches welcome to make our Windows build process fully reproducible, which would also solve that problem. I suspect that's a very tricky problem to solve, especially since we care about incremental builds working when possible. But if you want a fix on our side, at this point that's the only option I think I'd be open to.)

**Comment by magneticflux-** [comment]
I'm not sure where the Windows build scripts are right now (it seems like everything's moving to Nix?), but the fix _might_ be as easy as disabling timestamps when zipping using `7z`. Documentation on the command-line flags for 7-Zip is sparse, but I found these flags: https://superuser.com/a/831709. Adding `-mtm=off` should disable it.

Here's a patch for the `pre-nix` branch:
```patch
Index: buildbot/master.cfg
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/buildbot/master.cfg b/buildbot/master.cfg
--- a/buildbot/master.cfg	(revision fc7c033ee0a2845a71b0a37fc4ef029a9922877c)
+++ b/buildbot/master.cfg	(date 1674106110899)
@@ -202,7 +202,7 @@
                            hideStepIf=StepWasSuccessful))
 
     out_filename = WithProperties("Dolphin-%%s-%%s-%s.7z" % arch, "branchname", "shortrev")
-    f.addStep(ShellCommand(command=["7z", "a", "-r", out_filename,
+    f.addStep(ShellCommand(command=["7z", "a", "-r", "-mtm=off", out_filename,
                                     "Dolphin-%s" % arch],
                            logEnviron=False,
                            description="compressing",
```

**Comment by delroth** [comment]
I'll try to find some time to test it and apply it later this week -- I don't think it can hurt anyway. Thanks! But note that there *will* be intended cases where in fact we do end up with slightly different builds for the same version (example: changes on the build infra side are not captured in the dolphin-emu/dolphin revision hash). So thinking more about it, I don't actually believe making the build reproducible will completely solve your problem regardless.
